version: 2.1

workflows:
    workflow:
        jobs:
            -   build:
                    name: php-7.4-sylius-<< matrix.sylius_version >>-symfony-<< matrix.symfony_version >>
                    php_version: "7.4"
                    matrix:
                        parameters:
                            sylius_version: [ "1.8", "1.9", "1.10" ]
                            symfony_version: [ "4.4", "5.2" ]
                        exclude:
                            -   sylius_version: "1.8"
                                symfony_version: "5.2"
                            -   sylius_version: "1.9"
                                symfony_version: "5.2"
            -   build:
                    name: php-8.0-sylius-<< matrix.sylius_version >>-symfony-<< matrix.symfony_version >>
                    php_version: "8.0"
                    matrix:
                        parameters:
                            sylius_version: [ "1.10" ]
                            symfony_version: [ "5.2" ]

jobs:
    build:
        parameters:
            sylius_version:
                type: string
            symfony_version:
                type: string
            php_version:
                type: string
        docker:
            -   image: webdevops/php-nginx:<< parameters.php_version >>-alpine
        steps:
            -   checkout
            -   run: composer self-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/browser-kit:<< parameters.symfony_version >>.*" --no-interaction --no-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/debug-bundle:<< parameters.symfony_version >>.*" --no-interaction --no-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/dotenv:<< parameters.symfony_version >>.*" --no-interaction --no-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/intl:<< parameters.symfony_version >>.*" --no-interaction --no-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer require "symfony/web-profiler-bundle:<< parameters.symfony_version >>.*" --no-interaction --no-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer require "sylius/sylius:<< parameters.sylius_version >>.*" --no-interaction --no-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer require "doctrine/dbal:^2.6" --no-interaction --no-update
            -   run: COMPOSER_MEMORY_LIMIT=-1 composer update --no-interaction --prefer-dist
            -   run: (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
            -   run: (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
            -   run: (cd tests/Application && bin/console cache:warmup --env=test -vvv)
            -   run: ./bin/ecs.sh
            -   run: ./bin/phpstan.sh
            -   run: ./bin/behat
